changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Added
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
    - title: Compatibility
      labels:
        - compatibility
    - title: Documentation
      labels:
        - documentation
    - title: Maintenance
      labels:
        - dependencies
        - ci
        - maintenance
    - title: Other Changes
      labels:
        - "*"
